### ISSUE TITLE
I cannot subscribe to fragments of length 0

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zb-dispatcher#20]
* Offer/Claim fragment of length 0
* This fragment and any following fragment cannot be consumed by subscription

I guess this should check < 0: https://github.com/zeebe-io/zb-dispatcher/blob/0.1.0/dispatcher/src/main/java/io/zeebe/dispatcher/Subscription.java#L115

**Comment by ThorbenLindhauer** [comment]
We sometimes have the case that we write padding fragments of length 0. Subscriptions get stuck at those fragments. 

Implementation hint:

* both peek and poll should work with such fragments
* writing a fragment of length 0 is currently not thread-safe because we use the negative length to mark a fragment in progress and `-0 == 0`. We should use the one complement `~length` instead (=> `~0 == -1`).

**Comment by ThorbenLindhauer** [comment]
In Agrona's ring buffer implementations, this problem does not occur because the length includes the header length, i.e. `length >= 8` always holds.

**Comment by ThorbenLindhauer** [comment]
Implemented solution: 

We now include the dispatcher header length in the total length. This is a better solution than using the one complement, because it allows distinguishing the cases where a subscription consumes a fragment of net length 0 and where a subscription attempts to consume zeroed memory (=> this is possible when a new fragment is written in parallel).

**Comment by menski** [comment]
**Note**: This is a protocol-change which also have to adopt in the go client. @jsam
