### ISSUE TITLE
I cannot claim fragments where length = maxFrameLength

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zb-dispatcher#21]
* Max frame length suggests that it is inclusive
* https://github.com/zeebe-io/zb-dispatcher/blob/0.1.0/dispatcher/src/main/java/io/zeebe/dispatcher/Dispatcher.java#L238 should use <=

**Comment by menski** [comment]
moved to https://github.com/zeebe-io/zeebe/issues/490
