### ISSUE TITLE
offer() and claim() should return fragment offset

### ISSUE THREAD

**Issue by meyerdan** [zeebe-io/zb-dispatcher#5]
Currently the offer() and claim() methods return the "next position" ie. the position at which the next message would be written.
It would be probably better if the methods returned the position of the message which was written. This way, the position could be used to uniquely identitfy the message which was just written, not the "next message". It would then play the role of a unique message id and could also be passed in to the frame and block handlers.

**Comment by menski** [comment]
moved to https://github.com/zeebe-io/zeebe/issues/493
